kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pv-claim
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage

