apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: acc
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    name: https
    nodePort: 30443 
  selector:
    app: acc
