apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: acc
spec:
  type: NodePort
  ports:
  - port: 3443
    protocol: TCP
    targetPort: 3000
    nodePort: 30443
    name: https  
  selector:
    app: acc
