name:                accessibility
version:             0.1.0.0
github:              "dnulnets"
license:             BSD3
author:              "Tomas Stenlund"
maintainer:          "tomas.stenlund@telia.com"
copyright:           "2019 Tomas Stenlund"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gql#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options: []
  dependencies:
    - bytestring
    - morpheus-graphql
    - text
    - persistent
    - persistent-postgresql
    - persistent-template
    - yesod
    - yesod-auth
    - http-types
    - resourcet
    - monad-logger
    - lifted-base
    - yesod-core
    - aeson
    - cryptonite
    - containers
    - time
    - jwt
    - hexstring
    - wai-cors
    - wai
    - warp
    - time
    - hashable
    - path-pieces
    - nonce
    - base64-bytestring
    - unordered-containers
    - cereal
    - data-default
    - cookie
    - unliftio
    - warp-tls
    - yesod-static
    - wkt-geom
    - geojson
    - random
    - wai-app-static
    - time

executables:

  accessibility-server:
    main:                Main.hs
    source-dirs:         server
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accessibility

  hadmin:
    main:                Main.hs
    source-dirs:         hadmin
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accessibility
    - monad-logger
    - resourcet
    - bytestring
    - text
    - persistent-postgresql
    - persistent-template
    - persistent
    - mtl
    - aeson
    - aeson-pretty
    - time

tests:
  accessibility-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - accessibility
    - yesod-test
    - persistent
    - yesod
    - yesod-core
    - yesod-static
    - text
    - wai-app-static
    - wai-extra
    - random
    - mtl
    - persistent-postgresql
    - bytestring
    - monad-logger
    - http-types
    - case-insensitive
    - HUnit
    - aeson
    - time
    - containers
    - morpheus-graphql
    - hspec >= 2.0.0
