kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: data-pv-claim
  namespace: iothub
  labels:
    app: postgis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn

